### ISSUE TITLE
Не получается добавить его (jppm add jphp-udp-pingpong-ext@0.9.0)

### ISSUE THREAD

**Issue by yoricya** [LoveNek0/jphp-udp-pingpong-ext#1]
![Снимок экрана 2022-06-05 в 21 51 25](https://user-images.githubusercontent.com/63288807/172061394-fcb72b2f-5fe6-4880-9d35-6cdace97d0bb.png)
Что делать?

**Comment by lovenek0** [comment]
Обновил документацию, можешь использовать)
